version: "3.7"
services:
    php7.4-fpm:
        build:
            context: ./php7.4-fpm
        volumes:
            - /var/www/:/var/www/
        ports:
            - "9000:9000"

    php7.2-fpm:
        build:
            context: ./php7.2-fpm
        volumes:
            - /var/www/:/var/www/
        ports:
            - "9000:9000"

    php5.6-fpm:
        build:
            context: ./php5.6-fpm
        volumes:
            - /var/www/:/var/www/
        ports:
            - "9000:9000"
                            
    php5.3-fpm:
        build: 
            context: ./php5.3-fpm
        volumes:
            - /var/www/:/var/www/
        ports: 
            - "9000:9000"